// This Week file will get you to Generate a Sine Wave, store it in an Array and then report
// specific values from that array

#include <iostream>
#include <cmath>

using namespace std;

int main()
{
    // Create an array in Heap. Heap is the system RAM (generally) and allows massive arrays.
    float* Data = new float[1024]; //This creates an array called Data with 1024 points
    // The float* creates a pointer to a memory space where we have assigned 1024 floating points.
    
    int Fs = 44100;  //Sample Rate
    float freq = 441; // Frequency
    
    // For this test, you need to add the correct values into the sin() function below.
    // We have our sample rate (Fs) as an integer and freq as a float. Sin() requires a float input
    // To create a sine wave we use sin(wt) where w is the angular frequency and t is the time
    // Our t is in the digital domain and changes with the variable sample, generated by the for loop
    // and runs from 0 to value 1023. We can get t by multiplying sample by the period of 1 sample or 1/SampleRate
    
    // For w, we use 2pi*frequency. As a hint, cmath also defines certain math constants, including Pi, include
    // the definition for Pi from the cmath file include above.
    
    // The common failure of this test is placing an integer value in the sin function
    
    // As per before, give me the value it spits out, and send me your source code so I can check it.
    
    for (int sample = 0; sample < 1024; sample++){
        Data[sample] = sin();
    }
    
    cout << Data[201];
}