/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_9B600992__
#define __PLUGINEDITOR_H_9B600992__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class VstboilerPlateAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    VstboilerPlateAudioProcessorEditor (VstboilerPlateAudioProcessor* ownerFilter);
    ~VstboilerPlateAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_9B600992__
